id: P004417
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9801
  title: ཆོས་ཀྱི་བརྗེད་བྱང་།
  author: ''
  volumes:
    284ccd160ce14f239fa04ec47995158e:
      image_group_id: I1KG9818
      title: ''
      volume_number: 1
      total_pages: 602
