id: P004417
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG9801
  title: ཆོས་ཀྱི་བརྗེད་བྱང་།
  author: ''
  volumes:
    284ccd160ce14f239fa04ec47995158e:
      image_group_id: I1KG9818
      title: ''
      volume_number: 1
      total_pages: 602
      base_file: v001.txt
